{{- if (include "arkcase.vsdb.enabled" $) -}}
  {{- $ctx := $ -}}
  {{- $service := (include "arkcase.service.name" $ctx) -}}

  {{- $adminUser := "root" -}}
  {{-
    $usernameMap := dict
      "admin" $adminUser
  -}}
  
  {{- range $conn := (list "admin" "arkcase") }}
    {{- $secretName := (include "arkcase.subsystem-access.name" (dict "ctx" $ctx "conn" $conn)) }}
    {{- $secret := (include "arkcase.get-existing.secret" (dict "ctx" $ "name" $secretName) | fromYaml) }}
    {{- $secretData := $secret.data | default dict }}
    {{- $username := (get $usernameMap $conn | default $conn) }}
    {{- $username = $secretData.username | default $username }}
    {{- $password := $secretData.password | default (randAlphaNum 64) }}
    {{- $grpc := 443 }}
    {{- $rest := 8443 }}
    {{- $admin := 9091 }}
    {{- $database := ((eq $adminUser $username) | ternary "default" $username) }}
    {{- $collection := ((eq $adminUser $username) | ternary "" "acm_chatbot_embedding") }}

    {{-
      $data := dict
        "url" (printf "https://%s:%d/" $service $grpc)
        "rest" (printf "https://%s:%d/" $service $rest)
        "admin" (printf "http://%s:%d/" $service $admin)
        "type" "milvus"
        "username" $username
        "password" $password
        "token" (printf "%s:%s" $username $password)
        "database" $database
        "collection" $collection
    }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "arkcase.labels" $ | nindent 4 }}
    {{- with ($.Values.labels).common }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with ($.Values.annotations).common }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data: {{- include "arkcase.secret.encode" $data | nindent 2 }}
  {{- end }}
{{- end -}}

