#!/bin/bash

set -euo pipefail

say() {
	echo -e "$(date -Isec -u): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v DATA_DIR ] || DATA_DIR="${BASE_DIR}/data"
[ -v NEO4J_HOME ] || NEO4J_HOME="${BASE_DIR}/neo4j"
[ -v NEO4J_CONF ] || NEO4J_CONF="${BASE_DIR}/conf"

/update-ssl

# Are the databases already initialized?
DBS="$(find "${DATA_DIR}" -type f -name '*.db' | wc -l)"

if [ -v NEO4J_ADMIN_PASSWORD ] && [ -n "${NEO4J_ADMIN_PASSWORD}" ] && [ ${DBS} -eq 0 ] ; then
	# We only do this on the first boot ...
	say "Setting the admin password..."
	neo4j-admin set-initial-password "${NEO4J_ADMIN_PASSWORD}"
fi

say "Launching Neo4J..."
exec /usr/share/neo4j/bin/neo4j console --expand-commands
