#!/bin/bash

timestamp()
{
	/usr/bin/date -Ins
}

say()
{
	echo -e "$(timestamp): ${@}"
}

ok()
{
	say "✅ ${@}"
}

warn()
{
	say "⚠️ ${@}"
}

err()
{
	say "❌ ${@}" 1>&2
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

KUBECTL="$(type -P kubectl)" || fail "Could not find 'kubectl' in the path"
EGREP="$(type -P egrep)" || fail "Could not find 'egrep' in the path"
JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
AWK="$(type -P awk)" || fail "Could not find 'awk' in the path"
SED="$(type -P sed)" || fail "Could not find 'sed' in the path"
SORT="$(type -P sort)" || fail "Could not find 'sort' in the path"
TIMEOUT="$(type -P timeout)" || fail "Could not find 'timeout' in the path"

NSFLAG=()
if [ ${#} -gt 1 ] ; then
	say "👉 Will process ${#} PVCs given on the command line"
	ALL_PVC=("${@}")
else
	[ -v NAMESPACE ] || NAMESPACE="$("${KUBECTL}" config view --minify -o jsonpath="{..namespace}")"
	NSLABEL="current"
	if [ -n "${NAMESPACE}" ] ; then
		[[ "${NAMESPACE}" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]] || fail "The NAMESPACE value [${NAMESPACE}] is not valid"
		NSFLAG=(-n "${NAMESPACE}")

		"${KUBECTL}" get namespace "${NAMESPACE}" &>/dev/null || fail "The namespace [${NAMESPACE}] does not exist"
		NSLABEL="${NAMESPACE}"
	fi

	# Get all the PVCs in the currently default namespace
	say "👉 Listing all the PVCs in the ${NSLABEL} namespace..."
	readarray -t ALL_PVC < <("${KUBECTL}" get "${NSFLAG[@]}" pvc -o name 2>/dev/null | "${SED}" -e 's;^[^/]\+/;;g' | "${SORT}" -u)
	ok "Found ${#ALL_PVC[@]} PVCs"

	DEFAULT_NAMESPACE="${NAMESPACE}"
fi

[ -v ATTACHMENT_RESOURCE ] || ATTACHMENT_RESOURCE=""
[ -n "${ATTACHMENT_RESOURCE}" ] || ATTACHMENT_RESOURCE="volumeattachments.storage.k8s.io"

NODES="$("${KUBECTL}" get node -o name 2>/dev/null | "${SED}" -e 's;^[^/]\+/;;g' | "${SORT}" -u)"
[ -n "${NODES}" ] || fail "No cluster nodes found, cannot continue"

NSPREFIX=""
[ -n "${NAMESPACE}" ] && NSPREFIX="${NAMESPACE}::"
for PVC in "${ALL_PVC[@]}" ; do

	if [[ "${PVC}" =~ ^(([a-z0-9]([-a-z0-9]*[a-z0-9]))::)?([a-z0-9]([-a-z0-9]*[a-z0-9])?)$ ]] ; then
		NAMESPACE="${BASH_REMATCH[2]}"
		PVC="${BASH_REMATCH[4]}"
	else
		err "PVC name [${PVC}] is not valid"
		continue
	fi

	say "Scanning the ${NSLABEL} namespace for PVC ${PVC}..."

	if ! PV="$("${KUBECTL}" get pvc "${NSFLAG[@]}" "${PVC}" -o json | "${JQ}" -r '.spec.volumeName')" ; then
		err "No PVC [${PVC}] was found in the ${NSLABEL} namespace"
		continue
	fi

	if [ -z "${PV}" ] || ! "${KUBECTL}" get pv "${PV}" &>/dev/null ; then
		err "No volume ${PV} found ... referenced by PVC ${PVC}"
		continue
	fi

	# For each PVC, identify the pod(s) it's attached to

	readarray -t ATTACHMENTS < <("${KUBECTL}" get "${ATTACHMENT_RESOURCE}" 2>/dev/null | "${EGREP}" "\s${PV}\s" | "${AWK}" '{ print $1 }')

	say "${NSPREFIX}${PVC} - ${#ATTACHMENTS[@]} found"
	[ "${#ATTACHMENTS[@]}" -ge 1 ] || continue

	for ATTACHMENT in "${ATTACHMENTS[@]}" ; do
		if ! ATTACHMENT_INFO="$("${KUBECTL}" get "${ATTACHMENT_RESOURCE}" "${ATTACHMENT}" -o json)" ; then
			say "\t❌ the attachment ${ATTACHMENT} disappeared (${?})"
			continue
		fi

		DELETE="false"

		read ATTACHED NODE < <("${JQ}" -r '(.status.attached | tostring) + " " + .spec.nodeName' <<< "${ATTACHMENT_INFO}")
		if [ -z "${ATTACHED}" ] || [ -z "${NODE}" ] ; then
			# No node info?!?
			say "\t❌ the attachment [${ATTACHMENT}] has no node information... deleting"
			DELETE="true"
		else
			# TODO: Validate that the node exists....
			if "${KUBECTL}" get node "${NODE}" &>/dev/null ; then
				say "\t${ATTACHMENT} -> ${NODE} (${ATTACHED})"
			else
				say "\t❌ ${ATTACHMENT} -> ${NODE} is missing"
				DELETE="true"
			fi
		fi

		"${DELETE}" || continue

		RESULT="$("${TIMEOUT}" --k=15 10 "${KUBECTL}" delete "${ATTACHMENT_RESOURCE}" "${ATTACHMENT}" 2>&1)"
		RC=${?}
		if [ ${RC} -eq 0 ] ; then
			say "\t✅ ${RESULT}"
		else
			say "\t❌ Deletion failed (${RC})"
			say "\t❌ ${RESULT}"
		fi
	done
done
