#!/bin/bash

set -euo pipefail

timestamp()
{
	/usr/bin/date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

ok()
{
	say "✅ ${@}"
}

fail()
{
	say "❌ ${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

[ -v POD_NAME ] || POD_NAME=""
[ -n "${POD_NAME}" ] || POD_NAME="pvc-mounter"

KUBECTL="$(type -P kubectl)" || fail "Could not find 'kubectl' in the path"

NSFLAGS=()
[ -v NAMESPACE ] || NAMESPACE=""
[ -n "${NAMESPACE}" ] && NSFLAGS=(-n "${NAMESPACE}")

set -x
exec "${KUBECTL}" delete "${NSFLAGS[@]}" \
	{statefulsets.apps,configmaps,service}/"${POD_NAME}"
