#!/usr/bin/env python3

import argparse
import fcntl
import os
import signal
import subprocess
import sys
import time
import threading
import traceback
import datetime

import __main__ as main

SCRIPT_NAME = os.path.basename(main.__file__)

DEFAULT_TIMEOUT=10

MIN_BUFFER_SIZE_KB=1
DEFAULT_BUFFER_SIZE_KB=10
MAX_BUFFER_SIZE_KB=102400

parser = argparse.ArgumentParser(description = "Exit with a status code if data doesn't flow through this process (via STDIN/STDOUT) for a given amount of time")
parser.add_argument("-t", "--timeout", action="store", metavar="timeout", help=f"I/O Timeout (default {DEFAULT_TIMEOUT}s)", default=DEFAULT_TIMEOUT, type=int)
parser.add_argument("-i", "--stdin", action="store_true", help=f"Monitor data read from the subprocess's STDOUT")
parser.add_argument("-o", "--stdout", action="store_true", help=f"Monitor data written to the subprocess's STDIN")
parser.add_argument("-e", "--stderr", action="store_true", help=f"Monitor data read from the subprocess's STDERR")
parser.add_argument("-b", "--buffer", action="store", metavar="buffer", help=f"Size of the I/O buffer (default {DEFAULT_BUFFER_SIZE_KB}KB)", default=DEFAULT_BUFFER_SIZE_KB, type=int)
parser.add_argument("-d", "--debug", action="count", default=0, help="Enable debugging")
parser.add_argument("rest", nargs=argparse.REMAINDER)

cli = parser.parse_args()

#
# Ensure a valid timeout
#
TIMEOUT = DEFAULT_TIMEOUT
if cli.timeout < 0:
	TIMEOUT = 0
else:
	TIMEOUT = cli.timeout

#
# Ensure a sane buffer size
#
BUFFER_SIZE_BYTES = DEFAULT_BUFFER_SIZE_KB
if cli.buffer < MIN_BUFFER_SIZE_KB:
	BUFFER_SIZE_BYTES = MIN_BUFFER_SIZE_KB
elif cli.buffer > MAX_BUFFER_SIZE_KB:
	BUFFER_SIZE_BYTES = MAX_BUFFER_SIZE_KB

# Convert to bytes
BUFFER_SIZE_BYTES *= 1024

def error(message, *args):
	print(message, *args, file=sys.stderr, flush=True)

def fail(message, *args):
	error(message, *args)
	sys.exit(1)

class StreamThread(threading.Thread):
	def __init__(self, tracker, name, source, target):
		super(StreamThread, self).__init__(name=name, daemon=True)
		self.name = name
		self.tracker = tracker
		self.source = source
		self.target = target
		self.terminated = False

	def terminate(self):
		self.terminated = True

	def is_terminated(self):
		return self.terminated

	def terminate_and_join(self):
		self.terminate()
		self.join()

	def run(self):
		self.terminated = False
		try:
			fd = self.source.fileno()
			flags = fcntl.fcntl(fd, fcntl.F_GETFL)
			fcntl.fcntl(fd, fcntl.F_SETFL, flags | os.O_NONBLOCK)
			while (not self.terminated) and (not self.source.closed):
				data = self.source.read(BUFFER_SIZE_BYTES)

				if (data == None) or (len(data) == 0):
					LOG.debug(6, "Data read: {0}", data)
					os.sched_yield()
					continue

				if self.target.closed:
					LOG.debug(1, "The target stream was closed ({0})", self.name)
					break

				# We still have data, so touch the tracker if required
				self.tracker.touch()

				try:
					LOG.debug(4, "Writing out {0} bytes", len(data))

					if len(data) == 4:
						LOG.debug(5, "Writing out these 4 bytes: {0}", data)

					self.target.write(data)
					self.target.flush()
				except ValueError as e:
					LOG.debug(3, "ValueError caught: {0}", e)
					pass
		finally:
			LOG.debug(1, "Thread processing ended ({0} terminated={1})", self.name, self.terminated)

class Lock:
	def __init__(self, rwl, myEnter, myExit):
		self.rwl = rwl
		self.enter = myEnter
		self.exit = myExit

	def __enter__(self):
		return self.enter()

	def __exit__(self, exc_type, exc_value, traceback):
		return self.exit()

	def lock(self):
		return self.enter()

	def unlock(self):
		return self.__exit__(None, None, None)

class ReadWriteLock:
	def __init__(self):
		self.__read_condition = threading.Condition()
		self.__reader_count = 0
		self.__read_lock = Lock(self, self.__acquire_read, self.__release_read)
		self.__write_lock = Lock(self, self.__acquire_write, self.__release_write)

	def readLock(self):
		return self.__read_lock

	def writeLock(self):
		return self.__write_lock

	def __acquire_read(self):
		self.__read_condition.acquire()
		try:
			self.__reader_count += 1
		finally:
			self.__read_condition.release()

	def __release_read(self):
		self.__read_condition.acquire()
		try:
			self.__reader_count -= 1
			if not self.__reader_count:
				self.__read_condition.notify_all()
		finally:
			self.__read_condition.release()

	def __acquire_write(self):
		self.__read_condition.acquire()
		while self.__reader_count > 0:
			self.__read_condition.wait()

	def __release_write(self):
		self.__read_condition.release()

class TimeoutTracker:
	def __init__(self, timeout_seconds):
		self.timeout_seconds = timeout_seconds
		self.lock = ReadWriteLock()
		self.marker = time.time_ns()

	def touch(self):
		# Update the marker ... is there a faster way
		# to do this?
		now = time.time_ns()
		old = None
		with self.lock.writeLock():
			old = self.marker
			self.marker = now
		LOG.debug(2, "Marker touched (old = {0}, new = {1})", old, now)

	def expired(self):
		# If no timeout is set, or it's less than 1, then we never expire
		if ((self.timeout_seconds is None) or (self.timeout_seconds <= 0)):
			return False

		# Get the marker to compare against
		now = time.time_ns()

		# Get the number of seconds since now, and then
		elapsed = round((now - self.marker) / 1000000000)

		# Return True if more than timeout_seconds have passed
		return (elapsed >= self.timeout_seconds)

class Log:
	def __init__(self, exeName, level):
		self.level = level
		self.lock = ReadWriteLock()
		timestamp = time.strftime("%Y%m%d-%H%M%S")
		self.logName = f"{exeName}.{timestamp}.log"
		self.log = None
		self.init_log(level)

	def init_log(self, level):
		if self.log: return False
		if level < 1: return False

		self.log = open(self.logName, "at")

	def get(self):
		with self.lock.readLock():
			return self.level

	def grow(self):
		level = self.level + 1
		with self.lock.writeLock():
			self.level = level
			self.init_log(level)
			self.__print("Log level set to {0}", level)

	def __print(self, message, *args):
		if not self.log: return
		msg = message.format(*args)
		timestamp = time.strftime("%Y/%m/%d %H:%M:%S")
		thread = threading.current_thread().name
		print(f"{timestamp} [{thread}]: {msg}", file=self.log, flush=True)

	def debug(self, level, message, *args):
		if level <= self.get(): self.__print(message, *args)

	def dump_stacks(self):
		self.__print("Dumping stack traces")
		for th in threading.enumerate():
			self.__print(str(th))
			traceback.print_stack(f=sys._current_frames()[th.ident], file=self.log)
		self.__print("Stack traces complete")

def dump_stacks(sig, frame):
	LOG.dump_stacks()

def increase_log_level(sig, frame):
	LOG.grow()

if not cli.rest:
	fail("No command given, cannot continue")

# This object will track the last time I/O was detected
LOG = Log(sys.argv[0], cli.debug)

rc = 255
child = None
threads = []

LOG.debug(1, "Starting the timeout tracker")
tracker = TimeoutTracker(TIMEOUT);
try:
	LOG.debug(1, "Registering the USR1 signal handler (increase the logging level)")
	signal.signal(signal.SIGUSR1, increase_log_level)
	LOG.debug(1, "Registering the USR2 signal handler (dump stack traces)")
	signal.signal(signal.SIGUSR2, dump_stacks)

	_STDIN = None
	if cli.stdin: _STDIN = subprocess.PIPE
	_STDOUT = None
	if cli.stdout: _STDOUT = subprocess.PIPE
	_STDERR = None
	if cli.stderr: _STDERR = subprocess.PIPE

	LOG.debug(1, "Launching the child subprocess with {0}", cli.rest)
	child = subprocess.Popen(cli.rest, stdin=_STDIN, stdout=_STDOUT, stderr=_STDERR)

	if _STDIN:
		LOG.debug(2, "Creating the stdin thread")
		threads.append(StreamThread(tracker, "stdin", sys.stdin.buffer, child.stdin))

	if _STDOUT:
		LOG.debug(2, "Creating the stdout thread")
		threads.append(StreamThread(tracker, "stdout", child.stdout, sys.stdout.buffer))

	if _STDERR:
		LOG.debug(2, "Creating the stderr thread")
		threads.append(StreamThread(tracker, "stderr", child.stderr, sys.stderr.buffer))

	for t in threads:
		LOG.debug(2, "Starting the {0} thread", t.name)
		t.start()

	if threads:
		try:
			while True:
				# If the child process has terminated
				if child.poll() is not None:
					LOG.debug(1, "Child exited with code {0}", child.returncode)
					rc = child.returncode
					break

				# Still running? Check if the timeout has expired
				if tracker.expired():
					LOG.debug(1, "Timeout has expired, exiting")
					rc = 30
					break

				# No timeout yet? Sleep for exactly 1 second
				LOG.debug(3, "Sleeping for 0.2 second during poll")
				time.sleep(0.2)

		finally:
			for t in threads:
				LOG.debug(2, "Terminating the {0} thread", t.name)
				t.terminate_and_join()
	else:
		LOG.debug(1, "No monitoring configured, will just wait for the child process")
		child.wait()

except KeyboardInterrupt as e:
	LOG.debug(1, "Keyboard Interrupt caught, exiting")
	child_timeout = 30
	if child != None:
		LOG.debug(1, "Terminating the child process (pid={0})".format(child.pid))
		child.terminate()
		try:
			LOG.debug(1, "Waiting {0} seconds for the child to exit".format(child_timeout))
			child.wait(child_timeout)
		except subprocess.TimeoutExpired:
			error("Child process did not exit after {0} seconds, killing it".format(child_timeout))
			child.kill()
LOG.debug(1, "Exiting with RC={0}".format(rc))
sys.exit(rc)
