#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"

HELM_REPO_URL="https://arkcase.github.io/ark_helm_charts/"

set -euo pipefail

cd "${BASEDIR}"

#
# First things first, package the file
#
OUT="$(helm package charts/ark-common)"
helm repo index --url "${HELM_REPO_URL}" .

SRC="$(echo -n "${OUT}" | sed -e 's;^.*and saved it to: ;;g')"
ARCHIVES=()
find charts -type f -name 'ark-common-*.tgz'| while read f ; do
	CHARTSDIR="$(dirname "${f}")"
	MAINDIR="$(dirname "${CHARTSDIR}")"
	echo "${MAINDIR}"
	rm -fv "${f}"
	cp -vf "${SRC}" "${CHARTSDIR}"
	OUT="$(helm package "${MAINDIR}")"
	ARCHIVES+=("$(echo -n "${OUT}" | sed -e 's;^.*and saved it to: ;;g')")
done
