#!/bin/bash
CALLED="${BASH_ARGV0:-${BASH_SOURCE:-${0}}}"
SCRIPT="$(readlink -f "${CALLED}")"
BASEDIR="$(dirname "${SCRIPT}")"

set -euo pipefail

#
# This script helps to manage dependencies when one or more charts are updated.
# 
# It automatically triggers downstream builds as required on dependent charts.
#

say()
{
	echo -e "${@}"
}

doing()
{
	say "👉 ${@}"
}

ok()
{
	say "✅ ${@}"
}

warn()
{
	say "⚠️ ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

cleanup()
{
	[ -v WORKDIR ] && rm -rf "${WORKDIR}" &>/dev/null
}

usage()
{
	echo -e "usage: ${CALLED} source target-dir-1 [ target-dir-2 target-dir-3 ... target-dir-N ]"
	exit 1
}

package()
{
	local SRC="${1}"
	local WORKDIR="${2}"
	local PACKAGE=""
	OUT="$(helm package -d "${WORKDIR}" "${SRC}")" || return ${?}
	PACKAGE="$(echo -n "${OUT}" | sed -e 's;^.*and saved it to: ;;g')" || return ${?}
	[ -f "${PACKAGE}" ] || return 1
	echo -n "${PACKAGE}"
	return 0
}

[ ${#} -ge 2 ] || usage

SOURCE="${1}"
shift

WORKDIR="$(mktemp -d)"
trap cleanup EXIT

PACKAGE=""

for TARGET in "${@}" ; do
	if [ -z "${PACKAGE}" ] ; then
		doing "Packaging the chart from [${SOURCE}] ..."
		PACKAGE="$(package "${SOURCE}" "${WORKDIR}")" || fail "Failed to package the chart (rc=${?}): ${PACKAGE}"
		ok "The chart was packaged as $(basename "${PACKAGE}")"
	fi

	TARGET_CHARTS_DIR="${TARGET}/charts"
	[ -d "${TARGET_CHARTS_DIR}" ] || { err "No 'charts' directory for ${TARGET}" ; continue ; }

	rm -f "${TARGET_CHARTS_DIR}"/common-*.tgz &>/dev/null || true
	cp -vf "${PACKAGE}" "${TARGET_CHARTS_DIR}" &>/dev/null \
		&& ok "Chart deployed into ${TARGET}" \
		|| err "Failed to deploy the new common chart into ${CHART}"
done
