#!/bin/bash
helm repo update
find charts -type f -name 'ark-common-*.tgz'| while read f ; do
	D="$(dirname "${f}")"
	D="$(dirname "${D}")"
	echo "${D}"
	helm dependency update --skip-refresh "${D}" || break
done
