#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"

HELM_REPO_URL="https://arkcase.github.io/ark_helm_charts/"

set -euo pipefail

cd "${BASEDIR}"

#
# First things first, package the file
#
OUT="$(helm package charts/ark-common)"
helm repo index --url "${HELM_REPO_URL}" .

SRC="$(echo -n "${OUT}" | sed -e 's;^.*and saved it to: ;;g')"
ARCHIVES=()
while read f ; do
	CHARTSDIR="$(dirname "${f}")"
	MAINDIR="$(dirname "${CHARTSDIR}")"
	echo "${MAINDIR}"
	rm -fv "${f}"
	cp -vf "${SRC}" "${CHARTSDIR}"
	OUT="$(helm package "${MAINDIR}")"
	ARCHIVES+=("$(echo -n "${OUT}" | sed -e 's;^.*and saved it to: ;;g')")
done < <(find charts -type f -name "ark-common-*.tgz")

ARKCASE="charts/arkcase"
while read f ; do
	F="$(basename "${f}")"
	cp -vf "${F}" "${ARKCASE}/charts"
done < <(find "${ARKCASE}/charts" -type f -name "*.tgz")
