#!/bin/bash

timestamp() {
	/usr/bin/date -Isec -u
}

say() {
	echo -e "$(timestamp): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

set -euo pipefail

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v PENTAHO_HOME ] || PENTAHO_HOME="${BASE_DIR}/pentaho"

[ -v PENTAHO_SERVER ] || PENTAHO_SERVER="${PENTAHO_HOME}/pentaho-server"
[ -e "${PENTAHO_SERVER}" ] || fail "The Pentaho server directory could not be found at [${PENTAHO_SERVER}], cannot continue."
[ -d "${PENTAHO_SERVER}" ] || fail "The path [${PENTAHO_SERVER}] is not a directory, cannot continue."

###################################################################
# CONFIGURE FILESYSTEM PERSISTENCE								#
###################################################################
[ -v DATA_DIR ] || DATA_DIR="${BASE_DIR}/data"
[ -d "${DATA_DIR}" ] || mkdir -p "${DATA_DIR}"
export DATA_DIR

#
# ActiveMQ Persistence
#
ACTIVEMQ_DATA="${DATA_DIR}/activemq"
[ -d "${ACTIVEMQ_DATA}" ] || mkdir -p "${ACTIVEMQ_DATA}"
export ACTIVEMQ_DATA

#
# Configure Kettle
#
[ -v KETTLE_HOME ] || KETTLE_HOME="${DATA_DIR}/pdi"
[ -d "${KETTLE_HOME}" ] || mkdir -p "${KETTLE_HOME}"
export KETTLE_HOME



[ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"

###################################################################
# UPDATE CA CERTIFICATES										  #
###################################################################
/update-ssl

###################################################################
# INSTALL ANY LICENSES											#
###################################################################

#
# Configure license location
#
[ -v PENTAHO_INSTALLED_LICENSE_PATH ] || PENTAHO_INSTALLED_LICENSE_PATH="${DATA_DIR}/.installedLicenses.xml"
[ -f "${PENTAHO_INSTALLED_LICENSE_PATH}" ] || mkdir -p "$(dirname "${PENTAHO_INSTALLED_LICENSE_PATH}")"
export PENTAHO_INSTALLED_LICENSE_PATH

#
# Install the licenses
#
[ -v LICENSE_DIR ] || LICENSE_DIR="${INIT_DIR}/licenses"
if [ -d "${LICENSE_DIR}" ] ; then
	LICENSE_INSTALLER="${PENTAHO_HOME}/license-installer/install_license.sh"
	say "Installing all available license files from [${LICENSE_DIR}]"
	while read LICENSE ; do
		if /bin/sh "${LICENSE_INSTALLER}" install -q "${LICENSE}" ; then
			say "\tInstalled the license from [${LICENSE}], removing the original file"
			rm -fv "${LICENSE}" &>/dev/null || true
		else
			say "\tERROR: failed to install the license from [${LICENSE}]"
		fi
	done < <(find "${LICENSE_DIR}" -type f -name '*.lic' | sort)
fi

###################################################################
# CONFIGURE LOGGING											   #
###################################################################
[ -v LOGS_DIR ] || LOGS_DIR="${BASE_DIR}/logs"
[ -d "${LOGS_DIR}" ] || mkdir -p "${LOGS_DIR}"
export LOGS_DIR

#
# This is for debugging - if the log4j2 configuration isn't set already,
# we copy it from the base file
#
LOG4J2_XML="${PENTAHO_SERVER}/tomcat/webapps/pentaho/WEB-INF/classes/log4j2.xml"
[ -f "${LOG4J2_XML}" ] || cp -vf "${LOG$J2_XML}.base" "${LOG4J2_XML}" || fail "Failed to create the Log4J2 configuration"

#
# Tomcat Logging
#
[ -v TOMCAT_LOGS_DIR ] || TOMCAT_LOGS_DIR="${LOGS_DIR}/tomcat"
[ -d "${TOMCAT_LOGS_DIR}" ] || mkdir -p "${TOMCAT_LOGS_DIR}"
export TOMCAT_LOGS_DIR

[ -v INIT_MARKER ] || INIT_MARKER="${DATA_DIR}/.initialized"

# This is important: ${PENTAHO_HOME} must be *ephemeral* - this flag is only meant to
# inform when the init script ran, so we can run the post-init script in the helm chart
[ -v RUN_MARKER ] || RUN_MARKER="${PENTAHO_HOME}/.initRan"

###################################################################
# INITIALIZE PERSISTENT DATA AND CONFIGURATIONS				   #
###################################################################
if [ -e "${INIT_MARKER}" ] ; then
	say "Persistence is already initialized, proceeding with the normal boot"
else
	say "Persistence has not been initialized, proceeding with the first-time initialization"

	/config-pre.sh || fail "Pre-configuration failed - the Pentaho initialization may not be complete"

	touch "${INIT_MARKER}"
	touch "${RUN_MARKER}"
fi

###################################################################
# LAUNCH THE SERVER PROCESS									   #
###################################################################

CMD=("${PENTAHO_SERVER}/start-pentaho.sh" "${@}")
say "Launching Pentaho as: ${CMD[@]@Q}"
exec "${CMD}"
