{{- if and (include "arkcase.subsystem.enabled" $) (not (include "arkcase.subsystem.external" $)) }}
  {{- $cluster := (include "arkcase.cluster" $ | fromYaml) }}
  {{- $replicas := ($cluster.replicas | int) -}}
  {{- $scale := (include "arkcase.solr.scale" $ | fromYaml) -}}
  {{- $loss := ($scale.loss | atoi) -}}
  {{- if (ge $loss 1) -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "arkcase.fullname" $ | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  maxUnavailable: {{ $loss }}
  selector:
    matchLabels: {{- include "arkcase.labels.matchLabels" $ | nindent 6 }}
  {{- end -}}
{{- end -}}
