{{- if (include "arkcase.subsystem.enabled" $) -}}
  {{- $secretName := (include "arkcase.subsystem-access.name" $) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "arkcase.labels" $ | nindent 4 }}
    {{- with ($.Values.labels).common }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with ($.Values.annotations).common }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData: {{- include "arkcase.solr.scale" $ | nindent 2 -}}
{{- end -}}
