#!/bin/bash
set -euo pipefail

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v DEPL_DIR ] || DEPL_DIR="${BASE_DIR}/depl"
[ -v CONF_DIR ] || CONF_DIR="${DEPL_DIR}/conf"
[ -v WARS_DIR ] || WARS_DIR="${DEPL_DIR}/wars"

# Temporarily put them here... eventually they'll have
# a dedicated place to live
[ -v EXTS_DIR ] || EXTS_DIR="${CONF_DIR}"

say()
{
	echo -e "$(date -u -Ins): ${@}"
}

fail()
{
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

get_portal_war()
{
	local P=""
	local F=""
	for w in "${@}" ; do
		case "${w}" in
			*/portal.war ) P="${w}" ;;
			*/foia.war ) F="${w}" ;;
		esac
	done

	# If both are non-empty, we return an error
	[ -n "${P}" ] && [ -n "${F}" ] && return 1

	# This will result in the "winner" ... so spit out its name
	local W="${P}${F}"
	[ -n "${W}" ] && echo -n "${W}"
	return 0
}

[ -v SKIP_WARS ] || SKIP_WARS=""
[ -v SKIP_CONF ] || SKIP_CONF="false"

[ -v DEV ] || DEV="false"
case "${DEV,,}" in
	true | t | yes | y | on | en | enabled | enable | 1 ) DEV="true" ;;
	* ) DEV="false" ;;
esac

[ -v FORCE_DEPLOY ] || FORCE_DEPLOY="false"
case "${FORCE_DEPLOY,,}" in
	true | t | yes | y | on | en | enabled | enable | 1 ) FORCE_DEPLOY="true" ;;
	* ) FORCE_DEPLOY="false" ;;
esac

if ${DEV} ; then
	SKIP_WARS="$(echo "${SKIP_WARS}" | tr '/' '\n' | sort -u | sed -e '/^\s*$/d')"
	case "${SKIP_CONF,,}" in
		true | t | yes | y | on | en | enabled | enable | 1 ) SKIP_CONF="true" ;;
		* ) SKIP_CONF="false" ;;
	esac

	[ -v DEV_DIR ] || DEV_DIR="${BASE_DIR}/dev"
	DEV_WARS_DIR="${DEV_DIR}/wars"
	DEV_CONF_DIR="${DEV_DIR}/conf"
fi

#
# Deploy all WAR files
#
WAR="$(list-artifacts /arkcase/wars)" || fail "Failed to list the WAR files to be deployed"

readarray -t WAR < <(echo -n "${WAR}")

# Special case: sanitize the WAR list, make sure we have at most
# one of "portal.war" and "foia.war", because having both is a problem
PORTAL_WAR="$(get_portal_war "${WAR[@]}")" || fail "Cannot include multiple portal WAR files in the deployment - at most one is allowed!"

say "Found ${#WAR[@]} WAR files to deploy: [${WAR[@]}]"
for war in "${WAR[@]}" ; do

	ARTIFACT_NAME="${war##*/}"
	BASENAME="${ARTIFACT_NAME%.*}"

	# The default WAR's target is its basename without the extension
	# inside of WARS_DIR
	WAR_TGT="${BASENAME}"

	# If this is the Portal WAR, we can potentially pick where
	# it will be deployed into, other than the default path
	[ "${war}" == "${PORTAL_WAR}" ] && [ -v PORTAL_CONTEXT ] && WAR_TGT="${PORTAL_CONTEXT:-${WAR_TGT}}"

	# Pre-pend the actual target's parent directory
	WAR_TGT="${WARS_DIR}/${WAR_TGT}"

	if ${DEV} ; then
		WAR_PAT="${BASENAME}"

		# If we're in dev mode, then first we check to see if this
		# WAR is in the list of excluded WARs. We support treating
		# "foia" and "portal" as interchangeable (for now, at least)
		[ "${war}" == "${PORTAL_WAR}" ] && WAR_PAT="(portal|foia)"

		if egrep -q "^${WAR_PAT}$" <<< "${SKIP_WARS}" ; then
			say "The WAR file [${BASENAME}] is on the skip list, will ignore (matched /^${WAR_PAT}$/)"
			continue
		fi

		# This war is not excluded, so let's first check to see if
		# there's a development version of the WAR we should be
		# deploying instead
		if [ -s "${DEV_WARS_DIR}/${ARTIFACT_NAME}" ] ; then
			# We have a custom WAR to deploy! Use it!
			say "Found a development WAR at [${DEV_WARS_DIR}/${ARTIFACT_NAME}], will deploy it instead"
			mkdir -p "${WAR_TGT}"
			unzip -o -d "${WAR_TGT}" "${DEV_WARS_DIR}/${ARTIFACT_NAME}"
			continue
		fi
	fi

	mkdir -p "${WAR_TGT}" || fail "Failed to create the extraction target at [${WAR_TGT}]"

	# There's no development version, and the WAR is not excluded,
	# so let's go ahead and deploy it normally
	deploy-artifact extract "${war}" "${WAR_TGT}" || fail "Failed to deploy the WAR from [${war}] into [${WAR_TGT}]"
done

if ${DEV} ; then
	ARTIFACT_NAME="01-conf.zip"
	BASENAME="${ARTIFACT_NAME%.*}"

	if [ -s "${DEV_CONF_DIR}/${ARTIFACT_NAME}" ] ; then
		# We have a custom config to deploy! Use it!
		say "Found a development configuration at [${DEV_CONF_DIR}/${ARTIFACT_NAME}], will deploy it instead"
		unzip -o -d "${CONF_DIR}" "${DEV_CONF_DIR}/${ARTIFACT_NAME}"
		SKIP_CONF="true"
	fi
fi

if ! ${SKIP_CONF} ; then
	#
	# Deploy all the .arkcase configurations
	#
	CONF="$(list-artifacts /arkcase/conf)" || fail "Failed to list the CONF files to be deployed"
	readarray -t CONF < <(echo -n "${CONF}")
	say "Found ${#CONF[@]} CONF files to deploy: [${CONF[@]}]"
	for conf in "${CONF[@]}" ; do
		deploy-artifact extract "${conf}" "${CONF_DIR}" || fail "Failed to deploy the configuration from [${conf}]"
	done

	# Remove the contents of ${CONF_DIR}/custom/WEB-INF
	WEB_INF="${CONF_DIR}/custom/WEB-INF"
	if [ -e "${WEB_INF}" ] ; then
		say "Removing the existing extension binaries from [${WEB_INF}]..."
		rm -rf "${WEB_INF}"
	fi

	#
	# Deploy all the .arkcase extensions
	#
	EXTS="$(list-artifacts /arkcase/exts)" || fail "Failed to list the EXTS files to be deployed"
	readarray -t EXTS < <(echo -n "${EXTS}")
	say "Found ${#EXTS[@]} EXTS files to deploy: [${EXTS[@]}]"

	# Make sure the extensions are deployed ALWAYS
	(
		export FORCE_DEPLOY="true"
		for ext in "${EXTS[@]}" ; do
			deploy-artifact extract "${ext}" "${EXTS_DIR}" || fail "Failed to deploy the extension from [${ext}]"
		done
	) || exit ${?}
fi

#
# This is the only fix we know must be applied FOR SURE each time
#
realm-fix || fail "Failed to fix the realms information in the rules files"

[ -v OLD_URL ] || OLD_URL=""
[ -n "${OLD_URL}" ] || OLD_URL="https://project.armedia.com/nexus/"

[ -v NEW_URL ] || NEW_URL=""
[ -n "${NEW_URL}" ] || NEW_URL="https://nexus.armedia.com/"

# Do the YARNRC corrections
if [ "${OLD_URL}" != "${NEW_URL}" ] ; then
	FIRST="true"
	while read YARNRC ; do
		if "${FIRST}" ; then
			say "🔍 Will try to fix the .yarnrc files extracted in the WAR files"
			say "\tOld URL: [${OLD_URL}]"
			say "\tNew URL: [${NEW_URL}]"
			FIRST="false"
		fi

		[ -f "${YARNRC}" ] || continue
		[ -r "${YARNRC}" ] || continue
		[ -w "${YARNRC}" ] || continue
		say "🛠️ Attempting to fix the YARNRC file at [${YARNRC}]..."
		if sed -i -e "s|${OLD_URL}|${NEW_URL}|g" "${YARNRC}" ; then
			say "\t✅ Fixed!"
		else
			say "\t❌ Failed!"
		fi
	done < <(find "${DEPL_DIR}/wars" -type f -name .yarnrc | sort)
fi

say "✅ Configuration Initialization Complete"
exit 0
