#!/bin/bash
set -euo pipefail

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v DEPL_DIR ] || DEPL_DIR="${BASE_DIR}/depl"
[ -v CONF_DIR ] || CONF_DIR="${DEPL_DIR}/conf"

say() {
	echo -e "$(date -u -Ins): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

quit() {
	say "${@}"
	exit ${EXIT_CODE:-0}
}

[ -v REALM_FIX ] || quit "WARNING: No REALM_FIX found, will not modify the Excel files"
[[ "${REALM_FIX}" =~ ^([^=]+)=([^=]+)$ ]] || fail "The format for REALM_FIX is incorrect - must be 'OLD=NEW': [${REALM_FIX}]"

#
# If REALM_FIX is set, we edit the excel files accordingly
#

# REALM_FIX is set as "OLD_VALUE,NEW_VALUE", and three versions are created:
# literal (i.e. as-stated), lowercased, and uppercased

OLD="@${BASH_REMATCH[1]}"
NEW="@${BASH_REMATCH[2]}"

[ "${OLD}" == "${NEW}" ] && quit "The realm fix requested would have no effect (${OLD} == ${NEW})"

SUBS=("${OLD}" "${NEW}")
# If applicable, do the lowercased one
[ "${OLD,,}" != "${OLD}" ] && SUBS+=("${OLD,,}" "${NEW,,}")
# If applicable, do the uppercased one
[ "${OLD^^}" != "${OLD}" ] && SUBS+=("${OLD^^}" "${NEW^^}")

say "Finding the excel files from [${CONF_DIR}]..."
FILES="$(find "${CONF_DIR}" -type f -iname '*.xlsx' | sort | sed -e '/^$/d')"
TOTAL="$(echo -n "${FILES}" | wc -l)"
say "\t...found ${TOTAL} files"

[ ${TOTAL} -gt 0 ] || quit "No files found to repair"

COUNT=0
while read f ; do
	[ -n "${f}" ] || continue
	say "Fixing the Excel file [${f}] (file $(( COUNT + 1 ))/${TOTAL})..."
	fixExcel "${f}" "${SUBS[@]}" || fail "Failed to apply the realm fix for [${f}] (${COUNT}/${TOTAL} files processed successfully)"
	(( ++COUNT ))
done < <(echo -n "${FILES}")
say "Realm fixes completed on ${COUNT} files"
exit 0
