#!/bin/bash

set -euo pipefail

timestamp() {
	date -Ins
}

say() {
	echo -e "$(timestamp): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v SEED_DIR ] || SEED_DIR="${BASE_DIR}/seeds"

[ -d "${SEED_DIR}" ] || fail "The seed file directory [${SEED_DIR}] was not found"
SEED_DIR="$(readlink -f "${SEED_DIR}")" || fail "Failed to resolve the real path for the seed dir (rc=${?})"

while read FILE ; do
	say "Seeding LDAP based on the data from [${FILE}]..."
	init-seeds "${FILE}" || fail "Failed to initialize the seeds from [${FILE}]"
done < <(find "${SEED_DIR}" -type f -name 'seed-*.yaml' | sort -u)
exit 0
