#!/bin/bash

timestamp() {
	/usr/bin/date -Isec -u
}

say() {
	echo -e "$(timestamp): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

set -euo pipefail

#
# First things first: enable SSL
#
[ -v SSL_DIR ] || export SSL_DIR="/.ssl"

acme-init

[ -v SERVER_DIR ] || SERVER_DIR="${HOME_DIR}/server"
[ -v ETC_DIR ] || ETC_DIR="${SERVER_DIR}/etc"

[ -v JAVA_TOOL_OPTIONS ] || JAVA_TOOL_OPTIONS=""
JAVA_TOOL_OPTIONS+=" -Dorg.eclipse.jetty.ssl.keystore=${SSL_DIR}/keystore.pkcs12 -Dorg.eclipse.jetty.ssl.keypassword=$(<"${SSL_DIR}/keystore.pass") -Dzookeeper.client.secure=true "

#
# Now, continue with the boot
#

[ -v INIT_MARKER ] || INIT_MARKER="${DATA_DIR}/.initialized"

# This is important: ${HOME_DIR} must be *ephemeral* - this flag is only meant to
# inform when the init script ran, so we can run the post-init script in the helm chart
[ -v RUN_MARKER ] || RUN_MARKER="${HOME_DIR}/.initRan"

if [ -e "${INIT_MARKER}" ] ; then
	say "Persistence is already initialized, proceeding with the normal boot"
else
	say "Persistence has not been initialized, proceeding with the first-time initialization"

	/config-pre.sh || fail "Pre-configuration failed - the Solr initialization may not be complete"

	touch "${INIT_MARKER}"
	touch "${RUN_MARKER}"
fi

[ -v SOLR_LOGS_DIR ] || export SOLR_LOGS_DIR="${DATA_DIR}/logs"
[ -d "${SOLR_LOGS_DIR}" ] || mkdir -p "${SOLR_LOGS_DIR}" || say "WARNING: Failed to find and create the log directory at [${SOLR_LOGS_DIR}]"

if [ -v ZK_HOST ] ; then
	# Validate the hostnames
	readarray -d , -t FLAGS < <(echo -n "${ZK_HOST}")
	say "Validating the Zookeeper settings"
	ZK=()
	for H in "${FLAGS[@]}" ; do
		# Each host must be in the form hostname:port
		[ -n "${H}" ] || continue
		[[ "${H}" =~ ^([^:]+)(:([1-9][0-9]*))?$ ]] || fail "\tIgnoring the Zookeeper spec [${H}]: must be in the form \${hostname}:\${port}"

		HOST="${BASH_REMATCH[1]}"
		[[ "${HOST}" =~ ^([a-z0-9][-a-z0-9]*)?[a-z0-9]([.]([a-z0-9][-a-z0-9]*)?[a-z0-9])*$ ]] || fail "\tInvalid Zookeeper spec [${H}]: invalid host name [${HOST}]"

		PORT="${BASH_REMATCH[3]}"
		[ -z "${PORT}" ] && PORT="2181"
		[ ${PORT} -le 65535 ] || fail "\tInvalid Zookeeper spec [${H}]: invalid port number ${PORT}"

		say "\tAdding Zookeeper at ${HOST}:${PORT}"
		ZK+=("${HOST}:${PORT}")
	done

	say "Setting the ZK_HOST value [${ZK_HOST}]"
	export ZK_HOST="$(echo -n "${ZK[@]}" | tr ' ' ',')"
fi

set -- "${HOME_DIR}/bin/solr" start -f -cloud
say "Launching Solr as: ${@@Q}"
exec "${@}"
