{{- if and (include "arkcase.subsystem.enabled" $) -}}
  {{- $ctx := $ -}}
  {{- $db := (include "arkcase.db.info" $ctx | fromYaml) -}}
  {{- $secretName := (include "arkcase.subsystem-access.name" (dict "ctx" $ctx "conn" "db")) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "arkcase.labels" $ | nindent 4 }}
    {{- with ($.Values.labels).common }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with ($.Values.annotations).common }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  jdbcDriver: {{ $db.jdbc.driver | quote }}
  jdbcUrl: {{ $db.jdbc.url | quote }}
{{- end -}}
