#!/bin/bash

timestamp() {
	date -Ins -u
}

say() {
	echo -e "$(timestamp): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

set -euo pipefail

[ -v SSL_DIR ] || SSL_DIR="/.ssl"
CERT="${SSL_DIR}/haproxy-cert.pem"

[ -v MAX_WAIT ] || MAX_WAIT="30"
[[ "${MAX_WAIT}" =~ ^[1-9][0-9]*$ ]] || MAX_WAIT="30"

say "Waiting up to ${MAX_WAIT} seconds for the SSL certificates to become available"
START="$(date +%s)"
while true ; do
	[ -s "${CERT}" ] && [ -r "${CERT}" ] && break
	NOW="$(date +%s)"
	[ $(( NOW - START )) -lt ${MAX_WAIT} ] || fail "Timed out waiting for the SSL certificates to become available at [${CERT}]"
	sleep 1 || fail "Sleep interrupted, can't continue waiting for the certificate at [${CERT}]"
done

say "Launching HAProxy"
exec "/usr/local/bin/docker-entrypoint.sh" "/usr/local/sbin/haproxy" "-f" "/usr/local/etc/haproxy/haproxy.cfg"
