#!/bin/bash

set -euo pipefail

timestamp() {
	date -Ins -u
}

say() {
	echo -e "$(timestamp): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

usage() {
	echo -e "usage: ${BASH_SOURCE:-${0}} schema.xml"
	exit 1
}


[ -v ADMIN_USERNAME ] || ADMIN_USERNAME="admin"
[ -v ADMIN_PASSWORD ] || ADMIN_PASSWORD="password"
[ -v PENTAHO_URL ] || PENTAHO_URL="http://localhost:8080/pentaho"

[ ${#} -eq 1 ] || usage

SCHEMA_FILE="${1}"
[ -n "${SCHEMA_FILE}" ] || fail "The schema filename may not be the empty string"
[ -e "${SCHEMA_FILE}" ] || fail "The file [${SCHEMA_FILE}] does not exist"
[ -f "${SCHEMA_FILE}" ] || fail "The path [${SCHEMA_FILE}] is not a regular file"
[ -r "${SCHEMA_FILE}" ] || fail "The file [${SCHEMA_FILE}] is not readable"

case "${SCHEMA_FILE,,}" in
	*.xml ) ;;
	* ) fail "The schema file must have an extension of .xml (case-insensitive)" ;;
esac

SCHEMA_FILE="$(readlink -f "${SCHEMA_FILE}")"

xmllint --noout "${SCHEMA_FILE}" &>/dev/null || fail "The schema file at [${SCHEMA_FILE}] is not valid XML, can't install"

NAME="$(xmlstarlet sel -t -v "/Schema/@name" "${SCHEMA_FILE}")" || fail "Failed to parse the name out of the schema at [${SCHEMA_FILE}]"
[ -n "${NAME}" ] || fail "The Mondrian schema at [${SCHEMA_FILE}] lacks a name, can't install"

say "Installing the Mondrian schema [${NAME}] from [${SCHEMA_FILE}]..."
exec curl -kL -sS --fail \
	-H "Content-Type: multipart/form-data" \
	-X PUT \
	-F uploadInput="@${SCHEMA_FILE}" \
	-F overwrite="true" \
	-F xmlaEnabledFlag="false" \
	-F parameters="Datasource=ArkCase" \
	--config <(echo -n "--user \"${ADMIN_USERNAME}:${ADMIN_PASSWORD}\"") \
	"${PENTAHO_URL}/plugin/data-access/api/datasource/analysis/catalog/${NAME}"
