#!/bin/bash

set -euo pipefail

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v LOGS_DIR ] || LOGS_DIR="${BASE_DIR}/logs"
[ -v LOG_FILE ] || LOG_FILE="${LOGS_DIR}/foia-dw1.$(date -u +%Y%m%d-%H%M%SZ).log"
[ -v PENTAHO_PDI_HOME ] || PENTAHO_PDI_HOME="/app/pentaho-pdi"
[ -v FOIA_DIR ] || FOIA_DIR="${PENTAHO_PDI_HOME}/foia"
[ -v FOIA_JOB ] || FOIA_JOB="${FOIA_DIR}/foia-dw1.kjb"
[ -v KEEP_LOG ] || KEEP_LOG="30"

LOG_FLAG=()
[ -v LOG_LEVEL ] && [ -n "${LOG_LEVEL}" ] && LOG_FLAG=("-level:${LOG_LEVEL}")

echo "Logs will be stored at [${LOG_FILE}]"
(
	echo "Executing KJB: [${FOIA_JOB}]"
	cd "${PENTAHO_PDI_HOME}/data-integration"
	exec ./kitchen.sh -file:"${FOIA_JOB}" "${LOG_FLAG[@]}"
) |& tee "${LOG_FILE}"
for R in "${PIPESTATUS[@]}" ; do
	[ ${R} -eq 0 ] || exit ${R}
done

if [[ "${KEEP_LOG}" =~ ^[1-9][0-9]*$ ]] ; then
	# Delete all but the last KEEP_LOG logs
	echo "Will remove all but the last ${KEEP_LOG} logs"
	while read f ; do
		rm -fv "${f}" || true
	done < <(find "${LOGS_DIR}" -mindepth 1 -maxdepth 1 -type f -name 'foia-dw1.*.log' | sort | head -n -${KEEP_LOG})
else
	echo "KEEP_LOG is not a valid positive number (${KEEP_LOG}). Will not delete any old logs."
fi

exit 0
