#!/bin/bash

set -euo pipefail

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v DATA_DIR ] || DATA_DIR="${BASE_DIR}/data"
[ -v DWHS_DIR ] || DWHS_DIR="${DATA_DIR}/dw"
[ -v FOIA_DIR ] || FOIA_DIR="${DWHS_DIR}/foia"
[ -v FOIA_JOB ] || FOIA_JOB="${FOIA_DIR}/foia-dw1.kjb"
[ -v LOGS_DIR ] || LOGS_DIR="${BASE_DIR}/logs"
[ -v KEEP_LOG ] || KEEP_LOG="30"

[ -v PENTAHO_PDI_HOME ] || PENTAHO_PDI_HOME="${BASE_DIR}/pentaho-pdi"

LOG_FLAG=()
[ -v LOG_LEVEL ] && [ -n "${LOG_LEVEL}" ] && LOG_FLAG=("-level:${LOG_LEVEL}")

echo "Executing KJB: [${FOIA_JOB}]"
cd "${PENTAHO_PDI_HOME}/data-integration"
exec ./kitchen.sh -file:"${FOIA_JOB}" "${LOG_FLAG[@]}"
