#!/bin/bash

[ -v DEBUG ] || DEBUG="false"
case "${DEBUG,,}" in
	true | t | 1 | on | y | yes | enabled | enable | active ) DEBUG="true" ;;
	* ) DEBUG="false" ;;
esac

timestamp() {
	/usr/bin/date -Ins -u
}

say() {
	echo -e "$(timestamp): ${@}"
}

err() {
	say "ERROR: ${@}" 1>&2
}

fail() {
	say "${@}"
	exit ${EXIT_CODE:-1}
}

poll_url() {
	local URL="${1}"
	local START="$(date +%s)"
	say "Starting the polling cycle for [${URL}]..."
	while true ; do
		/usr/bin/curl -Lk -m 5 "${URL}" &>/dev/null && break
		local NOW="$(date +%s)"
		if [ $(( NOW - START )) -ge ${INIT_MAX_WAIT} ] ; then
			err "Timed out waiting for the URL [${URL}] to come up"
			return 1
		fi
		# If sleep didn't succeed, it means it got signaled, which
		# Means we need to stop what we're doing and puke out
		if ! sleep ${INIT_POLL_SLEEP} ; then
			err "Sleep interrupted, can't continue polling"
			return 1
		fi
	done
	say "The URL [${URL}] has responded, continuing"
	return 0
}

trap cleanup EXIT
set -euo pipefail

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v LOGS_DIR ] || LOGS_DIR="${BASE_DIR}/logs"
[ -v ADMIN_PORT ] || ADMIN_PORT="8443"

if [ -d "${LOGS_DIR}" ] ; then
	LOG_FILE="${LOGS_DIR}/first-boot.log"
	exec >> >(/usr/bin/tee -a "${LOG_FILE}")
	exec 2>&1
	say "Logs redirected to [${LOG_FILE}]"
fi

# By default, wait up to 300 seconds if not told otherwise
[ -v INIT_POLL_SLEEP ] || INIT_POLL_SLEEP=2
[[ "${INIT_POLL_SLEEP}" =~ ^[1-9][0-9]*$ ]] || INIT_POLL_SLEEP=2
[ -v INIT_MAX_WAIT ] || INIT_MAX_WAIT=900
[[ "${INIT_MAX_WAIT}" =~ ^[1-9][0-9]*$ ]] || INIT_MAX_WAIT=900

[ -v ADMIN_URL ] || ADMIN_URL="https://localhost:${ADMIN_PORT}/pentaho/"
poll_url "${ADMIN_URL}" || fail "Cannot continue configuration if Pentaho is not online"
