#!/bin/bash
set -euo pipefail

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"
[ -v REPS_DIR ] || REPS_DIR="${INIT_DIR}/reports"
[ -v DATA_DIR ] || DATA_DIR="${BASE_DIR}/data"
[ -v DWHS_DIR ] || DWHS_DIR="${DATA_DIR}/dw"
[ -v SUMS_FILE ] || SUMS_FILE="${INIT_DIR}/.artifact-sums"

say() {
	echo -e "$(date -u -Ins): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

if OUT="$(get-global-sums 2>&1)" ; then
	ARTIFACTS_SUM="$(jq -r '.pentaho // ""' <<< "${OUT}")"
	rm -f "${SUMS_FILE}" &>/dev/null
	[ -z "${ARTIFACTS_SUM}" ] || echo -n "${ARTIFACTS_SUM}" > "${SUMS_FILE}" || fail "Failed to render the artifacts sum file at [${SUMS_FILE}] with the value [${ARTIFACTS_SUM}]"
else
	warn "Failed to fetch the global artifact checksums (rc=${?}): ${OUT}"
fi

#
# Deploy all reports
#
REPORT="$(list-artifacts /pentaho/reports)" || fail "Failed to list the reports for deployment"
readarray -t REPORT < <(echo -n "${REPORT}")
say "Deploying ${#REPORT[@]} reports for automated installation: [${REPORT[@]}]"
mkdir -p "${REPS_DIR}"
for report in "${REPORT[@]}" ; do
	deploy-artifact copy "${report}" "${REPS_DIR}"
done

#
# Extract all the Data Warehousing stuff
#
DWHS="$(list-artifacts /pentaho/analytical)" || fail "Failed to list the analytical transformations for deployment"
readarray -t DWHS < <(echo -n "${DWHS}")
say "Deploying ${#DWHS[@]} Analytical Transformations: [${DWHS[@]}]"
mkdir -p "${DWHS_DIR}"
for dwhs in "${DWHS[@]}" ; do
	deploy-artifact extract-dir "${dwhs}" "${DWHS_DIR}"
done

say "Artifact deployment complete"
exit 0
