#!/bin/bash
set -euo pipefail

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"
[ -v DATA_DIR ] || DATA_DIR="${BASE_DIR}/data"

say() {
	echo -e "$(date -u -Ins): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

#
# Extract all the Data Warehousing stuff
#
say "Deploying Analytical Transformations"
DWHS="$(list-artifacts /pentaho/analytical)" || fail "Failed to list the analytical transformations for deployment"
readarray -t DWHS < <(echo -n "${DWHS}")
mkdir -p "${DATA_DIR}"
for dwhs in "${DWHS[@]}" ; do
	deploy-artifact extract-dir "${dwhs}" "${DATA_DIR}"
done

say "Artifact deployment complete"
exit 0
