#!/bin/bash
set -euo pipefail

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"
[ -v DEPL_DIR ] || DEPL_DIR="${BASE_DIR}/depl"
[ -v CONF_DIR ] || CONF_DIR="${DEPL_DIR}/conf"
[ -v WARS_DIR ] || WARS_DIR="${DEPL_DIR}/wars"

say() {
	echo -e "$(date -u -Isec): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}


#
# Deploy all WAR files
#
while read war ; do
	deploy-artifact extractdir "${war}" "${WARS_DIR}"
done < <(list-artifacts /arkcase/wars)

#
# Deploy all the .arkcase configurations
#
while read conf ; do
	deploy-artifact extract "${conf}" "${CONF_DIR}"
done < <(list-artifacts /arkcase/conf)

#
# This is the only fix we know must be applied FOR SURE each time
#
realm-fix

#
# Apply customizations and reconfigurations
#
if [ ! -d "${INIT_DIR}" ] ; then
	say "No initialization to perform, exiting"
	exit 0
fi

cd "${INIT_DIR}"
while read f ; do
	[ -s "${f}" ] || continue
	[ -r "${f}" ] || continue
	[ -x "${f}" ] || continue

	say "Executing initialization script [${f}]..."
	( "${f}" ) || fail "\tInitialization script [${f}] failed (rc=${?})"
done < <(list_files)

say "Configuration Initialization Complete"
exit 0
