#!/bin/bash

set -euo pipefail

say()
{
	echo -e "${@}"
}

fail()
{
	say "❌ ${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

#
# Ping Tomcat's internal communications port, which is only opened once
# Tomcat successfully completes its bootup sequence
#
MSG=""
[ ${#} -lt 1 ] || MSG="${@}"
[ -n "${MSG}" ] || MSG="PING"
( timeout --signal=KILL 5 echo -n "PROBE: ${MSG}" > "/dev/tcp/localhost/8005" ) &>/dev/null || fail "Tomcat is not started (${?})"

#
# All is well... ready to go!
#
say "✅ Tomcat is started!"
