apiVersion: v2
name: docscan
version: 0.10.0-1
appVersion: "3.3.1"
description: A Helm chart for all document-scanning servicesas used by ArkCase
type: application
dependencies:
  - name: common
    version: ~0.10.0-0
    repository: "https://arkcase.github.io/ark_helm_charts"
